name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: hit1
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Clean Azure Web App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group hit1
          az webapp delete-storage --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group hit1 || true
          az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group hit1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate deployment package
      run: |
        zip -r deployment.zip . -x "*.git*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
        package: deployment.zip

    - name: Restart Azure Web App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group hit1